### ISSUE TITLE
The 3D boards using HandleAdornments render much slower compared to parts

### ISSUE THREAD

**Issue by EthanCurtiss** [metauni/metaboard#12]
This is a screenshot of 100,000 non-overlapping parts being rendered at a consistent ~300 FPS.
![image](https://user-images.githubusercontent.com/41402526/147190921-b8a114e9-43d2-45c6-84bb-06c474ef21df.png)

This is a screenshot of 100,00 non-overlapping HandleAdornments being rendered at a consistent ~38 FPS.
![image](https://user-images.githubusercontent.com/41402526/147190960-c8900822-1176-4ed8-825b-7612c1d1caaf.png)

We should return to using parts for the 3D boards.

**Comment by metauni** [comment]
Resolved by 0c05e00694846df6ca910334f2ff3900d11eaf66 which switches back to Parts.
