### ISSUE TITLE
Indicator that you can't write on a board for permission reasons

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#31]
A user who can't write on a board can't tell if it's just that their stylus is low battery, or if they don't have permissions to write (and they may not even be aware that such permissions exist). There should be some kind of explanatory indicator on a board that does not allow you to write on it.

**Comment by billy-price** [comment]
I think the entire toolbar should just disappear, except the close button. The close button should live just outside the toolbar.

**Comment by dmurfet** [comment]
Doesn't moving the close button further right introduce a conflict with the leaderboard on the right hand side?

**Comment by billy-price** [comment]
The leaderboard is not there when the board gui is up.

The room taken up by the toolbar + close button would be the same regardless of whether the toolbar includes the close button or not. It's just a matter of the size of the grey rectangle indicating what's part of the toolbar.

**Comment by billy-price** [comment]
Added toolbar hiding in 89f527b
