### ISSUE TITLE
Performance benchmarking

### ISSUE THREAD

**Issue by EthanCurtiss** [metauni/metaboard#40]
There is a need for comparing performance between board versions. Some things we should measure:
* Drawing a single long line
* Drawing on a full board
* Erasing a full board
* Looking at a full 3D board
* Looking at a full 2D board
* How long in milliseconds certain API calls take

We should be able to run these benchmarks against multiple versions of the boards and have an easy way of comparing them.

**Comment by blinkybool** [comment]
Testing in general is probably a good idea. But I've been getting by just watching the microprofiler. I don't think there's a high priority need for this right now.
