### ISSUE TITLE
Toolbar doesn't catch tap events

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#5]
The toolbar should capture tap events. If you try to select tools with the Pencil, and miss, it causes the world camera to rotate.

**Comment by billy-price** [comment]
Fixed in [this commit](https://github.com/metauni/metaboard/commit/07e4b9fb6995419de832eb6b97f7d99bd806472a) and released [v0.2.2](https://github.com/metauni/metaboard/releases/tag/v0.2.2)
