### ISSUE TITLE
Mitigating flaws in Roblox's approach to private servers

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#50]
I am using private servers (e.g. https://www.roblox.com/games/8306474211/Circular-Concept) as spaces for writing on boards in the context of collaborations with students and others. It's useful because you can restrict the access to either particular accounts or to those with a particular URL. 

However, joining a private server is a chore because Roblox has set it up in a bad way. For example: if your friend is in a private server that you both have access to, and you click to "Join friend" on roblox.com, it will take you to the public server rather than the private server (which in the case of Circular Concept and the other metauni private servers, is disabled). So to join them you have to either (a) find the URL if you were given one or (b) click into the server, click on "Private servers" and click on "Join". This is a lot of friction.

@EthanCurtiss suggested the following approach which I like: the public server for Circular Concept can check to see if you joined the server following a friend (using `FollowUserId` https://developer.roblox.com/en-us/api-reference/property/Player/FollowUserId) and if you did, try to teleport you into the private server they are in. If you didn't follow a friend but *you* own a private version of the server, it should attempt to teleport you into that. So you can just click "Circular Concept" on the Roblox page and "Play" and it will do the thing you want it to do.

**Comment by BenSBk** [comment]
> If you didn't follow a friend but _you_ own a private version of the server, it should attempt to teleport you into that. So you can just click "Circular Concept" on the Roblox page and "Play" and it will do the thing you want it to do.

I don't think this is possible unless someone has already joined your private server so that the fact that you own it can be logged in a data store (`game.PrivateServerOwnerId`).

**Comment by dmurfet** [comment]
Resolved by pockets.
