### ISSUE TITLE
Eraser tool and thin lines

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#6]
Join with two accounts (I have one Mac, one iPad). Make line thickness as thin as possible, draw lines with one account and attempt to erase them with the small eraser on the other account. It doesn't always work.

**Comment by billy-price** [comment]
Fixed in [v0.2.4](https://github.com/metauni/metaboard/releases/tag/v0.2.4). It didn't seem to be line thickness related. Part of the issue was the lineInfo wasn't being updated after the first click, so you could only erase if you touch the start of the line.
