### ISSUE TITLE
Web-based board viewer

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#60]
Loading a board from a DataStore using the Cloud API and rendering it in a browser. No need for editing, but being able to download a PNG would be nice.

**Comment by phoebethewitch** [comment]
currently waiting for @billy-price for the persistence things

**Comment by dmurfet** [comment]
It would be useful if the web view had a URL to the pocket containing the board (if it is contained in a pocket, otherwise just the place URL). We can augment the launchData to include board persistIDs, so that when you join the pocket/experience you are then teleported directly in front of the board.

I would find this useful for meetings. I'm quite often saying in student meetings "let's revisit this calculation" where the calculation is on a metaboard somewhere. I have to remember where it is, then goto that pocket, it's fine but it is far from optimal. I should be able to just have some bookmarks in my browser or in a text file somewhere I can paste into a browser, and go straight to that board web view and then into the experience via deeplinking (checking the preview to make sure it's the right one).

**Comment by dmurfet** [comment]
Now available at service.metauni.org
