### ISSUE TITLE
Big blue dot and dead zones

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#7]
![IMG_0232](https://user-images.githubusercontent.com/320329/146894199-97cf4435-7be1-4207-a95a-b078637075aa.PNG)

This blue dot appeared on two boards (v0.2.5) in Deprecation just now in a conversation. Also you might see some scribble on the second line. I wrote a bunch of lines in the Canvas that just disappeared (not the straight line tool, normal lines). Apparently they appeared in the world but not in the Canvas.

**Comment by billy-price** [comment]
I think this is the same issue as #9

**Comment by metauni** [comment]
Resolved in v0.3.0
