### ISSUE TITLE
Unable to open board on iPad

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#87]
In a seminar, my iPad account (attached as drone) was able to initially open a board and write, but after closing the first board it was then unable to open any further boards. Tapping on them did nothing. The error message on the iPad client

![IMG_0287](https://user-images.githubusercontent.com/320329/209032365-2ee70a2a-c5ce-4465-b5e8-346f67dead97.PNG)
![IMG_0286](https://user-images.githubusercontent.com/320329/209032387-f3b028c8-c4a5-48a8-88cc-a8ed7d0c17c3.PNG)

On the desktop account there was the following (client) error, seems similar

<img width="1440" alt="Screen Shot 2022-12-22 at 10 59 53 am" src="https://user-images.githubusercontent.com/320329/209032420-b2fbd2f0-15a9-4da4-863b-97449e9795b4.png">

I will try again now without the drone/host mode

**Comment by dmurfet** [comment]
After unlinking the iPad account (it was a drone), I can still reproduce the above error and it actually crashes the Roblox client on my iPad a few seconds after tapping on the board.

**Comment by dmurfet** [comment]
Just got this in TRS (on v1.3.8)
![error](https://user-images.githubusercontent.com/320329/209244381-b383ffcd-e3c0-4d6b-8ed8-59baf6d94db0.png)

**Comment by blinkybool** [comment]
Both of these bugs were fixed.
