### ISSUE TITLE
Broken lines

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#9]
In v0.2.5, drawing on the Canvas, closing the canvas and then opening it again makes the appearance of text change. Sometimes lines are broken in spots, for example.

**Comment by dmurfet** [comment]
![IMG_0233](https://user-images.githubusercontent.com/320329/146895008-2492b516-6163-497f-8038-9546796f5ee0.PNG)

This H was a completely solid line when it was drawn. But closing the board and re-opening it turned it into this.

**Comment by dmurfet** [comment]
This is also present in v0.2.4. You can see in the attached pictures that it looks fine on my iPad (the one with the unbroken lines), but some of the lines are missing on my PC in both the Canvas and the world. Note also that the erase tool has removed the lines from the text that was previously on the board in the Canvas, but not completely from the world board.

![IMG_DE554E5A77FC-1](https://user-images.githubusercontent.com/320329/146919241-588d3594-2c47-4628-8c73-c341602c999e.jpeg)
<img width="1440" alt="Screen Shot 2021-12-21 at 8 56 51 pm" src="https://user-images.githubusercontent.com/320329/146919256-b3c3487b-a033-465e-b887-7715506689ce.png">
<img width="1440" alt="Screen Shot 2021-12-21 at 8 57 17 pm" src="https://user-images.githubusercontent.com/320329/146919259-d36e5680-e526-405a-9727-0f0506a8912d.png">

**Comment by dmurfet** [comment]
I cannot reproduce the issue on v0.2.3

**Comment by billy-price** [comment]
I turned off caching in v0.3.0, which "fixes" this problem. @dmurfet please verify you aren't experiencing this problem anymore when you get the chance.

**Comment by metauni** [comment]
Resolved in v0.3.0
